# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif
      pull-requests: write # needed to write pr decoration
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@749fec53e0db0f6404a97e2e0807c3e80e3583a7
        uses: checkmarx/ast-github-action@86e9ae570a811f9a1fb85903647a307aa3bf6253
        with:
          # Provide the AST portal URL
          base_uri: https://eu.ast.checkmarx.net/
          # Provide the Tenant for AST portal URL
          cx_tenant: test_naftali
          # Client ID for AST portal authentication
          cx_client_id: Akash_action
          # Secret key for AST portal authentication
          cx_client_secret: M1xTSEydsE5IimelSpthipORFBZcas5Z
          # Select a Checkmarx Project Name
          # GitHub API Token
          additional_params: --debug --report-format sarif --output-path .

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: cx_result.sarif
